apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    app: voting-app-demo
spec:
  selector:
    app: results-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
