apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting-app-demo
spec:
  selector:
    app: voting-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
